name: Build XCFramework

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build XCFramework
        run: $GITHUB_WORKSPACE/build-xcframework.sh
        
      - uses: actions/upload-artifact@v2
        with:
          name: XCFramework
          path: Frameworks 
          if-no-files-found: error
